name: Backend Format Check
on:
  push:
    branches: ["main"]
    paths:
      - "apps/backend/**"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "apps/backend/**"
jobs:
  backend-format-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run uvx ruff format --check
        run: uvx ruff format --check
