name: Frontend E2E Test
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: ${{ github.ref }}-frontend-e2e
  cancel-in-progress: true
on:
  push:
    branches: ["main"]
    paths:
      - "apps/frontend/**"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "apps/frontend/**"
jobs:
  frontend-e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Run npm run test:e2e
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        id: playwright-report
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: "apps/frontend//playwright-report/results.json"
          comment-title: "Frontend E2E Test Results"
          custom-info: "[Download full Report](${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.playwright-report.outputs.artifact-id }})"
